# Lokal konfiqurasiya — git-ə commit olunmur (.gitignore)
keycloak:
  client-secret: vnpAVHoUqur7A6DyHIdwQEjnnGmaLVCT

# Kafka lokal aktivasiya
app:
  kafka:
    enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
