spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 15MB
  cloud:
    gateway:
      routes:
          # Auth Service ucun
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1   # /api/auth/xyz -> /auth/xyz

          # Product Service ucun (backend @RequestMapping("/api/product") — prefix silinməməlidir)
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**

server:
  port: 8080


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 3600000
  refresh-expiration: 86400000